var collegeTable = {
    "Campus 2012 SAT/ACT: All Students, % Test": "CA0CT12R",
    "Campus 2012 SAT/ACT: All Students, % Above Criterion": "CA0CC12R",
    "Campus 2012 SAT/ACT: All Students, SAT Average": "CA0CSA12R",
    "Campus 2012 SAT/ACT: All Students, ACT Average": "CA0CAA12R",
    "CAMPUS 2012 College Ready: All Students Reading % Ready": "CACRR12R",
    "CAMPUS 2012 College Ready: All Students Math % Ready": "CACRM12R",
    "CAMPUS 2012 College Ready: All Students Both % Ready": "CACRB12R",


    "Campus 2011 College Ready: African American Reading % Ready": "CBCRR11R",
    "Campus 2011 College Ready: All Students Reading % Ready": "CACRR11R",
    "Campus 2011 College Ready: Asian Reading % Ready": "C3CRR11R",
    "Campus 2011 College Ready: At Risk Reading % Ready": "CRCRR11R",
    "Campus 2011 College Ready: Econ Disadv Reading % Ready": "CECRR11R",
    "Campus 2011 College Ready: Female Reading % Ready": "CFCRR11R",
    "Campus 2011 College Ready: Hispanic Reading % Ready": "CHCRR11R",
    "Campus 2011 College Ready: LEP Reading % Ready": "CLCRR11R",
    "Campus 2011 College Ready: Male Reading % Ready": "CMCRR11R",
    "Campus 2011 College Ready: Native American Reading % Ready": "CICRR11R",
    "Campus 2011 College Ready: Pacific Islander Reading % Ready": "C4CRR11R",
    "Campus 2011 College Ready: Special Ed Reading % Ready": "CSCRR11R",
    "Campus 2011 College Ready: Two or more Races Reading % Ready": "C2CRR11R",
    "Campus 2011 College Ready: White Reading % Ready": "CWCRR11R",
    "CAMPUS 2012 College Ready: African American Reading % Ready": "CBCRR12R",

    "CAMPUS 2012 College Ready: All Students Reading % Ready": "CACRR12R",
    "CAMPUS 2012 College Ready: Asian Reading % Ready": "C3CRR12R",
    "CAMPUS 2012 College Ready: At Risk Reading % Ready": "CRCRR12R",
    "CAMPUS 2012 College Ready: Econ Disadv Reading % Ready": "CECRR12R",
    "CAMPUS 2012 College Ready: Female Reading % Ready": "CFCRR12R",
    "CAMPUS 2012 College Ready: Hispanic Reading % Ready": "CHCRR12R",
    "CAMPUS 2012 College Ready: LEP Reading % Ready": "CLCRR12R",
    "CAMPUS 2012 College Ready: Male Reading % Ready": "CMCRR12R",
    "CAMPUS 2012 College Ready: Native American Reading % Ready": "CICRR12R",
    "CAMPUS 2012 College Ready: Pacific Islander Reading % Ready": "C4CRR12R",
    "CAMPUS 2012 College Ready: Special Ed Reading % Ready": "CSCRR12R",
    "CAMPUS 2012 College Ready: Two or more Races Reading % Ready": "C2CRR12R",
    "CAMPUS 2012 College Ready: White Reading % Ready": "CWCRR12R",
    "Campus 2011 College Ready: African American Math % Ready": "CBCRM11R",
    "Campus 2011 College Ready: All Students Math % Ready": "CACRM11R",
    "Campus 2011 College Ready: Asian Math % Ready": "C3CRM11R",
    "Campus 2011 College Ready: At Risk Math % Ready": "CRCRM11R",
    "Campus 2011 College Ready: Econ Disadv Math % Ready": "CECRM11R",
    "Campus 2011 College Ready: Female Math % Ready": "CFCRM11R",
    "Campus 2011 College Ready: Hispanic Math % Ready": "CHCRM11R",
    "Campus 2011 College Ready: LEP Math % Ready": "CLCRM11R",
    "Campus 2011 College Ready: Male Math % Ready": "CMCRM11R",
    "Campus 2011 College Ready: Native American Math % Ready": "CICRM11R",
    "Campus 2011 College Ready: Pacific Islander Math % Ready": "C4CRM11R",
    "Campus 2011 College Ready: Special Ed Math % Ready": "CSCRM11R",
    "Campus 2011 College Ready: Two or more Races Math % Ready": "C2CRM11R",
    "Campus 2011 College Ready: White Math % Ready": "CWCRM11R",
    "CAMPUS 2012 College Ready: African American Math % Ready": "CBCRM12R",

    "CAMPUS 2012 College Ready: All Students Math % Ready": "CACRM12R",
    "CAMPUS 2012 College Ready: Asian Math % Ready": "C3CRM12R",
    "CAMPUS 2012 College Ready: At Risk Math % Ready": "CRCRM12R",
    "CAMPUS 2012 College Ready: Econ Disadv Math % Ready": "CECRM12R",
    "CAMPUS 2012 College Ready: Female Math % Ready": "CFCRM12R",
    "CAMPUS 2012 College Ready: Hispanic Math % Ready": "CHCRM12R",
    "CAMPUS 2012 College Ready: LEP Math % Ready": "CLCRM12R",
    "CAMPUS 2012 College Ready: Male Math % Ready": "CMCRM12R",
    "CAMPUS 2012 College Ready: Native American Math % Ready": "CICRM12R",
    "CAMPUS 2012 College Ready: Pacific Islander Math % Ready": "C4CRM12R",
    "CAMPUS 2012 College Ready: Special Ed Math % Ready": "CSCRM12R",
    "CAMPUS 2012 College Ready: Two or more Races Math % Ready": "C2CRM12R",
    "CAMPUS 2012 College Ready: White Math % Ready": "CWCRM12R",
    "Campus 2011 College Ready: African American Both % Ready": "CBCRB11R",
    "Campus 2011 College Ready: All Students Both % Ready": "CACRB11R",
    "Campus 2011 College Ready: Asian Both % Ready": "C3CRB11R",
    "Campus 2011 College Ready: At Risk Both % Ready": "CRCRB11R",
    "Campus 2011 College Ready: Econ Disadv Both % Ready": "CECRB11R",
    "Campus 2011 College Ready: Female Both % Ready": "CFCRB11R",
    "Campus 2011 College Ready: Hispanic Both % Ready": "CHCRB11R",
    "Campus 2011 College Ready: LEP Both % Ready": "CLCRB11R",
    "Campus 2011 College Ready: Male Both % Ready": "CMCRB11R",
    "Campus 2011 College Ready: Native American Both % Ready": "CICRB11R",
    "Campus 2011 College Ready: Pacific Islander Both % Ready": "C4CRB11R",
    "Campus 2011 College Ready: Special Ed Both % Ready": "CSCRB11R",
    "Campus 2011 College Ready: Two or more Races Both % Ready": "C2CRB11R",
    "Campus 2011 College Ready: White Both % Ready": "CWCRB11R",
    "CAMPUS 2012 College Ready: African American Both % Ready": "CBCRB12R",

    "CAMPUS 2012 College Ready: All Students Both % Ready": "CACRB12R",
    "CAMPUS 2012 College Ready: Asian Both % Ready": "C3CRB12R",
    "CAMPUS 2012 College Ready: At Risk Both % Ready": "CRCRB12R",
    "CAMPUS 2012 College Ready: Econ Disadv Both % Ready": "CECRB12R",
    "CAMPUS 2012 College Ready: Female Both % Ready": "CFCRB12R",
    "CAMPUS 2012 College Ready: Hispanic Both % Ready": "CHCRB12R",
    "CAMPUS 2012 College Ready: LEP Both % Ready": "CLCRB12R",
    "CAMPUS 2012 College Ready: Male Both % Ready": "CMCRB12R",
    "CAMPUS 2012 College Ready: Native American Both % Ready": "CICRB12R",
    "CAMPUS 2012 College Ready: Pacific Islander Both % Ready": "C4CRB12R",
    "CAMPUS 2012 College Ready: Special Ed Both % Ready": "CSCRB12R",
    "CAMPUS 2012 College Ready: Two or more Races Both % Ready": "C2CRB12R",
    "CAMPUS 2012 College Ready: White Both % Ready": "CWCRB12R",
    "Campus 2011 SAT/ACT: African American % Test": "CB0CT11R",
    "Campus 2011 SAT/ACT: All Students % Test": "CA0CT11R",
    "Campus 2011 SAT/ACT: Asian % Test": "C30CT11R",
    "Campus 2011 SAT/ACT: Female % Test": "CF0CT11R",
    "Campus 2011 SAT/ACT: Hispanic % Test": "CH0CT11R",
    "Campus 2011 SAT/ACT: Male % Test": "CM0CT11R",
    "Campus 2011 SAT/ACT: Native American % Test": "CI0CT11R",
    "Campus 2011 SAT/ACT: Pacific Islander % Test": "C40CT11R",
    "Campus 2011 SAT/ACT: Two or More Races % Test": "C20CT11R",
    "Campus 2011 SAT/ACT: White % Test": "CW0CT11R",
    "Campus 2012 SAT/ACT: African American Students, % Test": "CB0CT12R",

    "Campus 2012 SAT/ACT: All Students, % Test": "CA0CT12R",
    "Campus 2012 SAT/ACT: American Indian Students, % Test": "CI0CT12R",
    "Campus 2012 SAT/ACT: Asian Students, % Test": "C30CT12R",
    "Campus 2012 SAT/ACT: Econ Disadv Students, % Test": "CE0CT12R",
    "Campus 2012 SAT/ACT: Female Students, % Test": "CF0CT12R",
    "Campus 2012 SAT/ACT: Hispanic Students, % Test": "CH0CT12R",
    "Campus 2012 SAT/ACT: Male Students, % Test": "CM0CT12R",
    "Campus 2012 SAT/ACT: Pacific Islander Students, % Test": "C40CT12R",
    "Campus 2012 SAT/ACT: Two or more races Students, % Test": "C20CT12R",
    "Campus 2012 SAT/ACT: White Students, % Test": "CW0CT12R",
    "Campus 2011 SAT/ACT: African American % Above Criterion": "CB0CC11R",
    "Campus 2011 SAT/ACT: All Students % Above Criterion": "CA0CC11R",
    "Campus 2011 SAT/ACT: Asian % Above Criterion": "C30CC11R",
    "Campus 2011 SAT/ACT: Female % Above Criterion": "CF0CC11R",
    "Campus 2011 SAT/ACT: Hispanic % Above Criterion": "CH0CC11R",
    "Campus 2011 SAT/ACT: Male % Above Criterion": "CM0CC11R",
    "Campus 2011 SAT/ACT: Native American % Above Criterion": "CI0CC11R",
    "Campus 2011 SAT/ACT: Pacific Islander % Above Criterion": "C40CC11R",
    "Campus 2011 SAT/ACT: Two or More Races % Above Criterion": "C20CC11R",
    "Campus 2011 SAT/ACT: White % Above Criterion": "CW0CC11R",
    "Campus 2012 SAT/ACT: African American Students, % Above Criterion": "CB0CC12R",

    "Campus 2012 SAT/ACT: All Students, % Above Criterion": "CA0CC12R",
    "Campus 2012 SAT/ACT: American Indian Students, % Above Criterion": "CI0CC12R",
    "Campus 2012 SAT/ACT: Asian Students, % Above Criterion": "C30CC12R",
    "Campus 2012 SAT/ACT: Econ Disadv Students, % Above Criterion": "CE0CC12R",
    "Campus 2012 SAT/ACT: Female Students, % Above Criterion": "CF0CC12R",
    "Campus 2012 SAT/ACT: Hispanic Students, % Above Criterion": "CH0CC12R",
    "Campus 2012 SAT/ACT: Male Students, % Above Criterion": "CM0CC12R",
    "Campus 2012 SAT/ACT: Pacific Islander Students, % Above Criterion": "C40CC12R",
    "Campus 2012 SAT/ACT: Two or more races Students, % Above Criterion": "C20CC12R",
    "Campus 2012 SAT/ACT: White Students, % Above Criterion": "CW0CC12R",
    "Campus 2012 SAT/ACT: African American Students, SAT Average": "CB0CSA12R",

    "Campus 2012 SAT/ACT: All Students, SAT Average": "CA0CSA12R",
    "Campus 2012 SAT/ACT: American Indian Students, SAT Average": "CI0CSA12R",
    "Campus 2012 SAT/ACT: Asian Students, SAT Average": "C30CSA12R",
    "Campus 2012 SAT/ACT: Econ Disadv Students, SAT Average": "CE0CSA12R",
    "Campus 2012 SAT/ACT: Female Students, SAT Average": "CF0CSA12R",
    "Campus 2012 SAT/ACT: Hispanic Students, SAT Average": "CH0CSA12R",
    "Campus 2012 SAT/ACT: Male Students, SAT Average": "CM0CSA12R",
    "Campus 2012 SAT/ACT: Pacific Islander Students, SAT Average": "C40CSA12R",
    "Campus 2012 SAT/ACT: Two or more races Students, SAT Average": "C20CSA12R",
    "Campus 2012 SAT/ACT: White Students, SAT Average": "CW0CSA12R",
    "Campus 2012 SAT/ACT: African American Students, ACT Average": "CB0CAA12R",

    "Campus 2012 SAT/ACT: All Students, ACT Average": "CA0CAA12R",
    "Campus 2012 SAT/ACT: American Indian Students, ACT Average": "CI0CAA12R",
    "Campus 2012 SAT/ACT: Asian Students, ACT Average": "C30CAA12R",
    "Campus 2012 SAT/ACT: Econ Disadv Students, ACT Average": "CE0CAA12R",
    "Campus 2012 SAT/ACT: Female Students, ACT Average": "CF0CAA12R",
    "Campus 2012 SAT/ACT: Hispanic Students, ACT Average": "CH0CAA12R",
    "Campus 2012 SAT/ACT: Male Students, ACT Average": "CM0CAA12R",
    "Campus 2012 SAT/ACT: Pacific Islander Students, ACT Average": "C40CAA12R",
    "Campus 2012 SAT/ACT: Two or more races Students, ACT Average": "C20CAA12R",
    "Campus 2012 SAT/ACT: White Students, ACT Average": "CW0CAA12R",
    "Campus 2011 SAT/ACT: African American Students Test": "CB0CA11R",
    "Campus 2011 SAT/ACT: All Students Test": "CA0CA11R",
    "Campus 2011 SAT/ACT: Asian Students Test": "C30CA11R",
    "Campus 2011 SAT/ACT: Female Students Test": "CF0CA11R",
    "Campus 2011 SAT/ACT: Hispanic Students Test": "CH0CA11R",
    "Campus 2011 SAT/ACT: Male Students Test": "CM0CA11R",
    "Campus 2011 SAT/ACT: Native American Students Test": "CI0CA11R",
    "Campus 2011 SAT/ACT: Pacific Islander Students Test": "C40CA11R",
    "Campus 2011 SAT/ACT: Two or More Races Students Test": "C20CA11R",
    "Campus 2011 SAT/ACT: White Students Test": "CW0CA11R"
};
